server:
  port: 8090


spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    #    url: jdbc:p6spy:mysql://172.16.10.12:3306/phdb_local?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    #    username: root
    #    password: Xxw@2019

    url: jdbc:p6spy:mysql://10.10.110.179:23306/phdb_dev?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: phdb_dev_user
    password: iuJfrk#PnS*oZ2UV
#    url: jdbc:p6spy:mysql://10.10.110.179:23306/migration?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#    username: phdb_wj_prod
#    password: w93G5!6u$k0718iu

#    url: jdbc:p6spy:mysql://10.10.110.179:23306/phdb_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#    username: phdb_test_user
#    password: w6H*OGxDLDn3O1jC
  redis:
    host: 10.10.110.74
    password: Xxw@2019
    port: 6789
    timeout: 10000 # 连接超时时间（毫秒）
    database: 1 # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0


#xxl:
#  job:
#    admin:
#      addresses: http://10.10.110.132:18100/xxl-job-admin/
#    executor:
#      appname: phdb-dev
eqb:
  notifyConfig:
    noticeDeveloperUrl: https://phdb-biz-service-dev.liuheco.com/v1/pad/eqb/callback#
  signConfig:
    redirectUrl: https://crpt-cloud-gateway-dev.liuheco.com/crpt-hybrid/views/phdb/callback-pages/index.html
  appId: 7438895808
  appSecret: 83b1ff1bf2939a944465bac47364da93
  apiUrl: https://smlopenapi.esign.cn
contract:
  url: https://oadev.liuheco.com
  username: db
  password: ZYMTndsW4uTnv3za
  signaddress: https://smlh5.esign.cn/usercenterFront/login/web?session=98b1b4b8-2ebf-4e08-a120-846ff5d3c6db&cusRedirectUrl=https%3A%2F%2Fsmlfront.esign.cn%3A8880%2Fworkspace%2Fallcompy
  apiUrl: https://smlopenapi.esign.cn

scfp:
  defaultDeptId: 100069
  defaultRoleId: 1644237262943621121
#  userUrl: http://127.0.0.1:14010/openapi/bff/get/code/relation/user
  callUrl: https://scfp-b-gateway-dev.liuheco.com/openapi/bff/third/part/input
  send:
    message: true
    creditMessageId: 1645668516030746625
    messageTurnToUrl: https://scfp-b-web-dev.liuheco.com/lark_login
    #messageTurnToUrl: http://172.18.7.197:8080/lark_login
  workflow:
    checkTurnToFGFZ: true
  #  userUrl: http://127.0.0.1:16000/openapi/bff/get/code/relation/user
  userUrl: https://scfp-b-gateway-test.liuheco.com/openapi/bff/get/code/relation/user

#E签宝三要素认证开关
eqbThreeFactor:
  #个人客户
  person:
    enable: false
  #企业客户
  corp:
    enable: true