server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      server-addr: 192.168.188.128:8848
    gateway:
      routes:
        - id: item-service
          uri: lb://item-service
          predicates:
            - Path=/items/**,/search/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**,/addresses/**